export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';
export const USER_LOGOUT = 'USER_LOGOUT';

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL';

export const UPDATE_PROFILE_REQUEST = 'UPDATE_PROFILE_REQUEST';
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';
export const UPDATE_PROFILE_FAIL = 'UPDATE_PROFILE_FAIL';
export const UPDATE_PROFILE_RESET = 'UPDATE_PROFILE_RESET';

export const USER_KEEP_LOGIN_DATA = 'USER_KEEP_LOGIN_DATA';
export const USER_KEEP_LOGIN_FAIL = 'USER_KEEP_LOGIN_DATA';
export const USER_KEEP_LOGOUT = 'USER_KEEP_LOGOUT';

export const USER_PROFILE_DATA = 'USER_PROFILE_DATA';
export const USER_PROFILE_FAIL = 'USER_PROFILE_FAIL';
export const USER_PROFILE_DELETE = 'USER_PROFILE_DELETE';

export const USERNAME_UPDATE_SUCCESS = 'USERNAME_UPDATE_SUCCESS';
export const USERNAME_UPDATE_FAIL = 'USERNAME_UPDATE_FAIL';

export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS';
export const CHANGE_PASSWORD_FAIL = 'CHANGE_PASSWORD_FAIL'; 